### ISSUE TITLE
Cave core is out of sync in HDMI

### ISSUE THREAD

**Issue by gkralicek** [turri21/Senhor#1]
When launching any game using the cave Senhor core, the video goes out of sync in HDMI (tried on 3 different TV sets and same result). No problem with all the other arcade, console or computer cores though...

**Comment by turri21** [comment]
Thank you very much for your feedback! I'm going to take a look at it tonight. I will try to fix it asap :)

**Comment by turri21** [comment]
I have an updated core. Let me know if it works for you now.
https://github.com/turri21/Senhor/blob/main/Arcade/cave/Cave_Senhor_20240705fixed.rbf

**Comment by gkralicek** [comment]
Just tried it and it works like a charm !!!!!! Thank you so much for finding out the problem, you're the best 👍. Do you think there is a chance that you could make some of the Jotego arcade cores compatible with this board (CPS 1 or CPS 2 for example) ?

**Comment by turri21** [comment]
> Just tried it and it works like a charm !!!!!! Thank you so much for finding out the problem, you're the best 👍. Do you think there is a chance that you could make some of the Jotego arcade cores compatible with this board (CPS 1 or CPS 2 for example) ?

You are welcome! Have fun! Regarding the rest of the cores (including the Jotego cores) our intentions is to port every single one of them, so it is just a matter of time ;)
