### ISSUE TITLE
PSX core is losing sync from time to time

### ISSUE THREAD

**Issue by tdelage26** [turri21/Senhor#2]
When using HDMI connection on an LCD screen or Scart Connection on a CRT via direct video, the video is losing sync and there is a black screen that can last 3 or 4 seconds before the signal is  back.

**Comment by turri21** [comment]
It seems that some cores are a bit more "sensitive" than the avg and even though they are stable in some setups they can be unstable in others, like in your case. That alone makes it even harder to recreate and identify the issue, but also it's the best proof of how much of a help is to get a feedback from you (much appreciated!).  
Anyway, already looking at it and hopefully I'll get back to you asap with a fix.
Cheers!

**Comment by turri21** [comment]
Let's see what kind of stability do you get with this:
https://github.com/turri21/Senhor/blob/main/Consoles/PSX/temp/PSX_20240402.rbf

**Comment by tdelage26** [comment]
I just tested and with that new version it seems super stable on both my LCD in HDMI and in CRT, no more sync loss but i noticed that when using Direct Video on CRT i got freezes from time to time (i don't have that problem through HDMI at all)

**Comment by turri21** [comment]
Awesome! This core has a major disadvantage though. It has the video signals mapped to physical pins on the board, in other words, you may gain stability, but you have to sacrifice these free pins in relation to a potential future expansion, such as an analog I/O addon board. It is a quick and dirty solution, but not a perfect one... Therefore, I will keep it in the temp folder for now until we can find something better.
Regarding the direct video, do you get this problem only on the PSX core? Did you try anything else with it?

**Comment by tdelage26** [comment]
Yes it's the only core having problem with analog direct video. There are some random pauses occuring from time to time, mostly when a game loads and you got an intro video, it usually freezes a few seconds after the intro has started or sometimes right after a game has been started. It's really weird as far as when switching to hdmi profile the problem disappear and everything runs smooth without a hitch. I can try and make a tiny video to show the problem if it can help.

**Comment by turri21** [comment]
It's ok you described it very well! Ok I will keep that in mind and I'll see what I can do. I have some ideas, one might be to compare a working core with it and see what's the difference in direct video that may have been causing this issue.

**Comment by turri21** [comment]
Let's see if this one will do the trick:
https://github.com/turri21/Senhor/blob/main/Consoles/PSX/temp/PSX_Senhor_20240418v2.rbf

**Comment by tdelage26** [comment]
Nope still the same. Random freezing in Direct Video but everything is perfect through HDMI

**Comment by turri21** [comment]
ok I'm gonna gamble a bit. My bet is that this "wire hdmi_blackout" is causing the issue. It is not present in the N64, Saturn and other cores. So I'm gonna remove it completely from the PSX core.

**Comment by turri21** [comment]
Here it is: https://github.com/turri21/Senhor/blob/main/Consoles/PSX/temp/PSX_Senhor_20240418v3.rbf
Fingers crossed...

**Comment by tdelage26** [comment]
Last version doesn't solve the problem and adds a lot of visual artifacting (coloured lines) in HDMI while loading. I think i found the reason of those random freezing. In the main osd menu from the core there is an option in the "miscellanious" menu where you can deactivate "pause when CD slow". Doing so and being warned it could make the core unstable it solved all the freezing problems.... So all in all the best update of all is the first version you had made as it solved all the sync problems with both HDMI and Direct Video.

Aside from this, i've notice the last version of menu.rbf you uploaded doesn't sync properly in HDMI anymore (no problem with analog direct video). Same goes for the JT1943 core.

Anyway thanks for all the tremendous job you are doing with this board !! 👍👍

**Comment by turri21** [comment]
Great find, since it works for you!
Btw I'd like to see your MiSTer.ini if you can paste it over there: https://pastebin.com/   it will be great.
I will focus on PSX_Senhor_20240418v2.rbf, because I have made some important changes in order not to reserve any of the physical pins. 

About the 1943 core, since it is part of the Jotego cores it will take some time until we get a decent result, because I have to "fight" 2x monsters... One is the MiSTer framework and the second is the Jotego framework ugh... 
Last but not least, regarding the menu, get the one that works best for you from there: https://github.com/turri21/Menu_Senhor/releases until I come up with a general solution for everyone (hopefully...)
 
Cheers, I would like to thank you as well for your detailed and valuable feedbacks!

**Comment by tdelage26** [comment]
The MiSTer.ini i use is the standard one available here : https://github.com/MiSTer-devel/Main_MiSTer/blob/master/MiSTer.ini
When switching to analog, i use an alternate version which is the same except with direct_video =1 and  hdmi_limited=2 to get the proper colour range.

**Comment by turri21** [comment]
> The MiSTer.ini i use is the standard one available here : https://github.com/MiSTer-devel/Main_MiSTer/blob/master/MiSTer.ini When switching to analog, i use an alternate version which is the same except with direct_video =1 and hdmi_limited=2 to get the proper colour range.

Yes these are the right settings for analog. For HDMI you could try this one, it is using a custom video mode:
https://github.com/turri21/Senhor/blob/main/MiSTer.ini 

video_mode=1920,1080,60,-hsync,+vsync

**Comment by turri21** [comment]
The guys on telegram just told me that 1943 v0.3 is stable. If you haven't tried it already, give it a shot!
https://github.com/turri21/Senhor/blob/main/Arcade/Jotego/jt1943_Senhor_v0.3.rbf

**Comment by tdelage26** [comment]
Yeah i can indeed confirm v0.3 is stable. I have no problem with it both through HDMI and Direct Video 👍
